module.exports = {
  RECEIVED_FRIENDS: "RECEIVED_FRIENDS",
  RECEIVE_NEW_FRIEND: "RECEIVE_NEW_FRIEND",
  RECEIVED_FRIENDSHIP: "RECEIVED_FRIENDSHIP",
  ADDED_FRIEND: "ADDED_FRIEND",
  CONFIRMED_FRIEND: "CONFIRMED_FRIEND",
  CANCEL_FRIEND: "CANCEL_FRIEND"
};
