module.exports = {
  RECEIVED_ITEMS: "RECEIVED_ITEMS",
  RECEIVE_UPDATED_COMMENT: "RECEIVE_UPDATED_COMMENT",
  NEW_COMMENT_MADE_ON_TIMELINE: "NEW_COMMENT_MADE_ON_TIMELINE",
  RECEIVE_UPDATED_POST: "RECEIVE_UPDATED_POST",
  DELETE_POST_COMMENT: "DELETE_POST_COMMENT",
  DELETE_PHOTO_COMMENT: "DELETE_PHOTO_COMMENT"
};
