module.exports = {
  RECEIVED_ITEMS: "RECEIVED_ITEMS",
  NEW_COMMENT_MADE_ON_TIMELINE: "NEW_COMMENT_MADE_ON_TIMELINE",
  RECEIVE_UPDATED_POST: "RECEIVE_UPDATED_POST",
  DELETE_TIMELINE_POST_COMMENT: "DELETE_TIMELINE_POST_COMMENT"
};
