module.exports = {
  RECEIVED_ITEMS: "RECEIVED_ITEMS",
  RECEIVE_UPDATED_COMMENT: "RECEIVE_UPDATED_COMMENT",
  RECEIVE_UPDATED_POST: "RECEIVE_UPDATED_POST",
  DELETE_POST_COMMENT: "DELETE_POST_COMMENT"
};
